#include <Szachy/Dane_poczatkowe/daneliczbowe.h>
u_short uliczba_3=3;
u_short uliczba_2=2;
u_short uliczba_1=1;
u_short uliczba_0=0;
u_short uliczba_4=4;
u_short uliczba_5=5;
u_short Tutaju_short;
int Tutajint;
bool Tutajbool;

short Tutajshort;
bool bool_0=0;
bool bool_1=1;
short liczba_2=2;
short liczba_3=3;
short liczba_1=1;
short liczba_0=0;
short liczba_01=-1;
